### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by jhonpanteraaa** [pyrosec/tinder#3]
> tinder init
> tinder auth-login --phone-number 19701823918
> tinder verify-otp --phone-number 19701823918 --otp 858192
> tinder use-email --email testemail@gmail.com
> tinder start-onboarding
> tinder set-name --name 'Dave'
> tinder set-birth-date --birth-date '1996-01-02'
> tinder set-gender --gender 0
> tinder set-interested-in-gender --gender 1
> tinder set-school --school-id ope_350031 --name 'New York University' --displayed
> tinder set-interests
> tinder onboarding-autocomplete

After executing the last command I get an error

>  tinder onboarding-autocomplete
> FetchError: invalid json response body at https://api.gotinder.com/v2/onboarding/autocomplete reason: Unexpected end of JSON input
>     at /usr/local/share/.config/yarn/global/node_modules/node-fetch/lib/index.js:273:32
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async TinderClient.onboardingAutocomplete (/usr/local/share/.config/yarn/global/node_modules/tinder/lib/tinder.js:743:16)
>     at async callAPI (/usr/local/share/.config/yarn/global/node_modules/tinder/lib/cli.js:107:20)
>     at async runCLI (/usr/local/share/.config/yarn/global/node_modules/tinder/lib/cli.js:238:20)
>     at async /usr/local/share/.config/yarn/global/node_modules/tinder/bin/tinder.js:6:3 {
>   type: 'invalid-json'
> }

Could you help me? The order of the commands may have changed

**Comment by jhonpanteraaa** [comment]
@pyrosec
